### ISSUE TITLE
Create a hit point system and collision detection for attacking

### ISSUE THREAD

**Issue by LanceBailey** [GamesByMoonlight/CandyReaper#3]
Create a hitpoint tracking system

Create a method so that an attack can be registered to remove hit points from the target

**Comment by OccidoVirus** [comment]
I've been adding HP variables to all the Player Character BP's I've made thus far.
Integers; 'CurHP' & 'MaxHP'.

I've defaulted 'MaxHP' to 100, and have 'CurHP' set itself equal to 'MaxHP' on 'BeginPlay' within each Character BP.
