### ISSUE TITLE
Begin assembling extra 3D assets

### ISSUE THREAD

**Issue by LanceBailey** [GamesByMoonlight/CandyReaper#4]
Check sites like opengameart.org or other links from the wiki (and if you find anything new, add it to the google doc) to find/implement new spooky art that may not be available in the Paragon assets.

Remember to make a note of web site URL and artist name when downloading assets.

**Comment by Merg12** [comment]
I just uploaded several Halloween themed assets, I also have a google spreadsheet for website, URL and artist name

**Comment by Ember-Rane** [comment]
Nice, I saw these. Some are already working inside of the game. Others need to be 'put together' or something, like the spiders legs are separate. This should be easy, but I haven't done it before.
