### ISSUE TITLE
Create a level with the terrain tools

### ISSUE THREAD

**Issue by LanceBailey** [GamesByMoonlight/CandyReaper#6]
Investigate how to use the terrain modification tools in Unreal

Build a level using the terrain sculpting tools in Unreal

Create/import art assets if needed

**Comment by myantstew** [comment]
Created the neighborhood level - playing area. I think Cisco is going to add the terrain and environmental items.

**Comment by Ember-Rane** [comment]
Do you have a branch for this? I created a map called Level One for just setting things up, but planned on turning it into a player select screen later. Just want to make sure we don't have the same name for things or something.

**Comment by myantstew** [comment]
I have MikesLevel in the maps folder. Still some work to do but it's coming along.
